version: "3.9"
services:

  mongodb-primary:
    image: mongo:5.0
    container_name: mongodb1
    hostname: mongodb1
    command: --bind_ip_all --replSet mongo-replica
    networks:
      mongodb_network:
    volumes:
      - mongodb_data_1:/data/modelDb
    expose:
      - 27017

  mongodb-secondary-1:
    image: mongo:5.0
    container_name: mongodb2
    hostname: mongodb2
    command: --bind_ip_all --replSet mongo-replica
    networks:
      mongodb_network:
    volumes:
      - mongodb_data_2:/data/modelDb
    expose:
      - 27017

  mongodb-secondary-2:
    image: mongo:5.0
    container_name: mongodb3
    hostname: mongodb3
    command: --bind_ip_all --replSet mongo-replica
    networks:
      mongodb_network:
    environment:
      DB: modelDb
    volumes:
      - mongodb_data_3:/data/modelDb
      - ./scripts:/scripts
    expose:
      - 27017

  mongosetup:
    image: mongo:5.0
    depends_on:
      - mongodb-primary
      - mongodb-secondary-1
      - mongodb-secondary-2
    restart: "no"
    networks:
      mongodb_network:
    volumes:
      - ./scripts:/scripts
    environment:
      DB: modelDb
    entrypoint: [ "bash", "-c", "sh ./scripts/mongo_setup.sh"]

volumes:
  mongodb_data_1:
  mongodb_data_2:
  mongodb_data_3:

networks:
  mongodb_network: